namespace :smartdiab do
  "Load default medications"
  task init_medication: :environment do
    if MedicationType.all.size != 0
      MedicationType.all.each {|mt|
        mt.destroy!
      }
    end
    oral_med_list = [
      "Actos",
      "Actos 15 mg",
      "Actos 30 mg",
      "Actos 45 mg",
      "Amaryl 1",
      "Amaryl 2",
      "Amaryl 3",
      "Amaryl 4",
      "Amaryl 5",
      "Amaryl 6",
      "Atoris",
      "Atoris 30 mg",
      "Atoris 60 mg",
      "Atoris 80 mg",
      "Avamina",
      "Avamina 1000 mg",
      "Avamina 500 mg",
      "Avamina 850 mg",
      "Avandia",
      "Diabetol",
      "Diamicron",
      "Fenofibrate",
      "Glibenclamide",
      "Gliclazide",
      "Glimepiride",
      "Glipizide",
      "Glucophage",
      "Glucophage 1000 mg",
      "Glucophage 500 mg",
      "Glucophage 850 mg",
      "Glucophage XR",
      "Glucovance",
      "Glumetza",
      "Glyburide",
      "Janumet",
      "Metformin"
    ]
    insulin_list = [ "Actraphane 10 NovoLet",
        "Actraphane 20 NovoLet",
        "Actraphane 30 FlexPen",
        "Actraphane 40 NovoLet",
        "Actraphane 50 NovoLet",
        "Actrapid",
        "Apidra",
        "Exubera",
        "Gensulin M10 (10/90)",
        "Gensulin M20 (20/80)",
        "Gensulin M30 (30/70)",
        "Gensulin M40 (40/60)",
        "Gensulin M50 (50/50)",
        "Gensulin N",
        "Gensulin R",
        "Humalog",
        "Humalog Mix 25",
        "Humalog Mix 50",
        "Humalog NPL",
        "Humulin 50/50",
        "Humulin 70/30",
        "Humulin L",
        "Humulin M2",
        "Humulin M3",
        "Humulin N",
        "Humulin R",
        "Humulin U",
        "Insulatard",
        "Insulin Human Winthrop Bosal",
        "Insulin Human Winthrop Comb 15",
        "Insulin Human Winthrop Comb 25",
        "Insulin Human Winthrop Comb 50",
        "Insulin Human Winthrop Infusat",
        "Insulin Human Winthrop Rapid",
        "Insulinum Isophanicum ChO-S",
        "Insulinum Isophanicum WOS alto depuratum",
        "Insulinum Lente ChO-S",
        "Insulinum Lente WO-S alto depuratum",
        "Insulinum Maxirapid ChO-S",
        "Insulinum Maxirapid WO-S alto depuratum",
        "Insulinum Semilente ChO-S",
        "Insulinum Semilente WO-S alto depuratum",
        "Insulinum Solutio Neutralis ChO-S",
        "Insulinum Solutio Neutralis WO-S alto depuratum",
        "Insulinum Ultralente ChO-S",
        "Insulinum Ultralente WO-S alto depuratum",
        "Insuman Bosal",
        "Insuman Comb 15",
        "Insuman Comb 25",
        "Insuman Comb 50",
        "Insuman Infusat",
        "Insuman Rapid",
        "Iso-Mix 3 WO-S",
        "Iso-Mix 4 WO-S",
        "Iso-Mix 5 WO-S",
        "Lantus",
        "LENTE WO-S ",
        "Levemir",
        "Liprolog",
        "Liprolog Mix 25",
        "Liprolog Mix 50",
        "MAXIRAPID ChO-S",
        "MAXIRAPID WO-S",
        "Mixtard 10",
        "Mixtard 20",
        "Mixtard 30",
        "Mixtard 40",
        "Mixtard 50",
        "NovoMix 30",
        "NovoMix 50",
        "NovoMix 70",
        "NovoRapid",
        "Optisulin",
        "Polhumin Mix 2",
        "Polhumin Mix 3",
        "Polhumin Mix 4",
        "Polhumin Mix 5",
        "Polhumin N",
        "Polhumin R",
        "Protaphane",
        "SEMILENTE ChO-S",
        "SOLUTIO NEUTRALIS WO-S",
        "Velosulin"]

        oral_med_list.each {|om|
          mt = MedicationType.new(:name => om, :group => "oral")
          mt.save!
        }
        insulin_list.each {|ins|
          mt = MedicationType.new(:name => ins, :group => "insulin")
          mt.save!
        }

end
end
